### ISSUE TITLE
id doesn't have correct type convertor

### ISSUE THREAD

**Issue by yorkie** [weflex/neaty#3]
Even though we define id to be a `String` value, when we put a string like `ObjectId`, the type of it in MongoDB still to be a `ObjectId` type.

**Comment by scottoasis** [comment]
Interesting. If MongoDB was that smart, there won't be any problem filtering objects.

**Comment by yorkie** [comment]
Nope, unfortunately this is a bug of this library and we have to fix it :-(

**Comment by scottoasis** [comment]
LOL. I see.

**Comment by yorkie** [comment]
This is a bug in loopback-connector-mongodb, and fixed it at https://github.com/weflex/neaty-connector-mongodb/commit/074e70e6f8380a4da92e53cde4dcaa3eff595308.

**Comment by scottoasis** [comment]
@yorkie Awesome! Can we use ObjectIds as our filtering conditions now?

**Comment by yorkie** [comment]
@scottoasis do you mean:

```
userId: {
  in: [
    'userId-a', 'userId-b'
  ]
}
```

And https://github.com/weflex/api/blob/gateway/server/boot/data.js#L28-L30 is the working example :-)
